version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - webapp-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - webapp-network

networks:
  webapp-network:
    driver: bridge
