version: '3.8'

services:
  frontend:
    image: nginx:latest
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - webapp-network

  backend:
    image: node:14
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
    command: ["npm", "start"]
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - webapp-network

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - webapp-network

networks:
  webapp-network:
    driver: bridge

volumes:
  db-data:
